config/routes.rb
Rails.application.routes.draw do

  get 'calendar/new'

  devise_for :users, :controllers => {:registrations => "registrations"}
  root to: 'static_pages#home'
  resource :workitem
  resource :event
  get '/dashboard' => 'dashboard#new'
  get '/workestimate' => 'workitems#totalwork'
  put '/deactivateTask' => 'workitems#deactivate'
  get '/eventsToday' => 'workitems#events_today'
  get '/weeklySummary' => 'dashboard#weekly_summary'
  as :user do
    get "/login" => "devise/sessions#new"
    get "/signup" => "registrations#new"
  end

end

app/views/nav/_nav.html.erb
<nav class="navbar navbar-default custom-nav" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">CalTime</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= cp(root_path) %>"><a href="/">Home<span class="sr-only"></span></a></li>
        <% if user_signed_in? %>
          <li class="<%= cp(dashboard_path) %>"><a href="/dashboard">Dashboard<span class="sr-only"></span></a></li>
        <% end %>
       
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
          <li class="<%= cp(login_path) %>"><%= link_to "Login", login_path%></li>
          <li class="<%= cp(signup_path) %>"><%= link_to "Sign up", signup_path%></li>
        <% end %>
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            </ul>
        </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>